spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: false
graphiql:
  enabled: true
  cdn:
    enabled: false
    version: 0.17.5
  headers:
    Test: TestHeader
  props:
    variables:
      headerEditorEnabled: true
      headers: '{ "Authorization": "SomeValue" }'
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false
